---
layout: cv

---

# Karen Olguin
Business Analytics Student | Summer Analyst | Quality Assurance Auditor

<div id="webaddress">
<a href="mailto:karenolguinliz@gmail.com">karenolguinliz@gmail.com</a>
| <a href="https://www.linkedin.com/in/karenolguinl">linkedin.com/in/karenolguinl</a>
| 208.973.8558
</div>

## Education

`September 2021 - April 2025`  
__Brigham Young University - Idaho__, Rexburg, ID  
- Bachelor of Science in Business Analytics  
- Minors: Finance, Financial Planning  
- Scholarship: Brigham Young University - Idaho Academic Grant (2021 - 2024)  
- Tools: Power BI, Python, Excel, Alteryx, Tableau, MySQL, RStudio  

## Experience

`June - August 2024`  
__Goldman Sachs__, Salt Lake City, UT  
*Summer Analyst, Operations - PWM*  
- Automated trade booking process using Alteryx and Tableau, saving 1.5 hours daily and reducing manual errors.  
- Implemented JIRA frameworks to improve workload visibility, progress tracking, and deadlines.  
- Streamlined homepage resources, reducing tool search time by 30%.  

`Brigham Young University - Idaho`, Rexburg, ID  
*IT Quality Assurance Auditor*  
- Audited analysts' work and provided feedback, improving process quality from 92% to 97%.  
- Delivered bi-weekly training sessions to enhance technical and customer service skills.  

*IT Analyst*  
- Resolved technical needs for 23+ users daily via phone, email, and chat using tools like Team Dynamix, Zoom, and Zoho Assist.  
- Solved over 700 incidents related to technological errors and service requests.  

## Volunteer Experience

`July 2018 - September 2020`  
__The Church of Jesus Christ of Latter-day Saints__, Mexico City, Mexico  
*Full-time Volunteer Representative*  
- Examined team statistics to improve training meetings and teaching methods.  
- Increased service request efficiency from 25% to 36% by creating Excel report models and forecasting future needs.  

## Projects

__Quality Student Consultant__ (July 2023)  
- Analyzed employee performance using Power BI charts in bi-weekly reports to generate key insights and improve analysts' productivity.  

---